version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./app:/app"
    command: make dev
  caddy:
    image: caddy:2.7
    volumes:
      - "./app/services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - app