FROM node:14.19.3

RUN apt-get update \
    && apt-get install -yq make

WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

EXPOSE 8080

CMD npm start
