version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    command: ["bash", "-c", "sleep 3 && npm start"]

  caddy:
    image: caddy:2.7
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - app