name: push in app

on: push

jobs:
  push-app:
    runs-on: ubuntu-latest
    steps:
      - name: copy git dir
        uses: actions/checkout@v3
      - name: print path
        run: make -f app/Docker-makefile path
      - name: docker build
        run: make -f app/Docker-makefile build-compose -e FILE_PATH=app/docker-compose.yml
      - name: run tests
        run: make -f app/Docker-makefile docker-app-test -e FILE_PATH=app/docker-compose.yml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make -f app/Docker-makefile push-image -e FILE_PATH=app/docker-compose.yml
