name: push in app

on: push

env:
  DOCKER_COMPOSE_PATH: "app/docker-compose.yml"
  DOCKER_MAKEFILE_PATH: "app/Docker-makefile"
  IMAGE_NAME: "shabelnikilya/devops-for-programmers-project-74"

jobs:
  push-app:
    runs-on: ubuntu-latest
    steps:
      - name: copy git dir
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker build
        run: make -f "${{ env.DOCKER_MAKEFILE_PATH }}" build-compose -e FILE_PATH="${{ env.DOCKER_COMPOSE_PATH }}"
      - name: run tests
        run: make -f "${{ env.DOCKER_MAKEFILE_PATH }}" docker-app-test -e FILE_PATH="${{ env.DOCKER_COMPOSE_PATH }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build app and push to docker hub
        uses: docker/build-push-action@v3
        with:
          context: app
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline
          push: true
          tags: ${{ env.IMAGE_NAME }}
#      - run: make -f "${{ env.DOCKER_MAKEFILE_PATH }}" push-image -e FILE_PATH="${{ env.DOCKER_COMPOSE_PATH }}"
